In [3]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv("Downloads/Home_Price.csv")
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [11]:
dummies = pd.get_dummies(df.town)
dummies

monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

In [13]:
merged = pd.concat([df, dummies], axis = 1)
merged


town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000             True        False         False
1   monroe township  3000  565000             True        False         False
2   monroe township  3200  610000             True        False         False
3   monroe township  3600  680000             True        False         False
4   monroe township  4000  725000             True        False         False
5      west windsor  2600  585000            False        False          True
6      west windsor  2800  615000            False        False          True
7      west windsor  3300  650000            False        False          True
8      west windsor  3600  710000            False        False          True
9       robinsville  2600  575000            False         True         False
10      robinsville  2900  600000            False         True         False
11      robinsville  3100  620000            False         True         False
12      robinsville  3600  695000            False         True         False

In [29]:
final = merged.drop(['town', 'west windsor'], axis = 1)
final

area   price  monroe township  robinsville
0   2600  550000             True        False
1   3000  565000             True        False
2   3200  610000             True        False
3   3600  680000             True        False
4   4000  725000             True        False
5   2600  585000            False        False
6   2800  615000            False        False
7   3300  650000            False        False
8   3600  710000            False        False
9   2600  575000            False         True
10  2900  600000            False         True
11  3100  620000            False         True
12  3600  695000            False         True

In [33]:
final['monroe township'] = final['monroe township'].map({True:1, False:0})
final['robinsville'] = final['robinsville'].map({True:1, False:0})
final

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [39]:
model = linear_model.LinearRegression()
model.fit (final[['area', 'monroe township', 'robinsville']], final.price)

LinearRegression()

In [41]:
model.predict([[2800, 0, 1]])

C:\Users\Ravi Kiran\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.63964739])

In [45]:
import warnings
warnings.filterwarnings('ignore')

In [47]:
model.predict([[3000, 0, 0]])

array([630482.69189422])

In [51]:
x = final[['area', 'monroe township', 'robinsville']]
y = final['price']
model.score(x,y)

0.9573929037221871

In [53]:
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [55]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()


In [57]:
dfle = df
dfle['town'] = le.fit_transform(dfle['town'])
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [59]:
y = dfle['price']
X = dfle.drop(['price'], axis = 1)
X

town  area
0      0  2600
1      0  3000
2      0  3200
3      0  3600
4      0  4000
5      2  2600
6      2  2800
7      2  3300
8      2  3600
9      1  2600
10     1  2900
11     1  3100
12     1  3600

In [63]:
model.fit(X,y)

LinearRegression()

In [67]:
model.predict([[2,3300]])

array([670283.67762584])

In [69]:
model.score(X,y)

0.9552018104317441

In [71]:
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [85]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [113]:
X = ohe.fit_transform(dfle[['town']]).toarray()
X

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [115]:
X = X[:, 1:]
Z = pd.DataFrame(X)
X = pd.concat([Z, dfle.area], axis = 1)
X

0    1  area
0   0.0  0.0  2600
1   0.0  0.0  3000
2   0.0  0.0  3200
3   0.0  0.0  3600
4   0.0  0.0  4000
5   0.0  1.0  2600
6   0.0  1.0  2800
7   0.0  1.0  3300
8   0.0  1.0  3600
9   1.0  0.0  2600
10  1.0  0.0  2900
11  1.0  0.0  3100
12  1.0  0.0  3600

In [131]:
model.fit(X.astype(int),dfle.price)

TypeError: Feature names are only supported if all input features have string names, but your input has ['int', 'str'] as feature name / column name types. If you want feature names to be stored and validated, you must convert them all to strings, by using X.columns = X.columns.astype(str) for example. Otherwise you can remove feature / column names from your input data, or convert them all to a non-string data type.